<h1>Rapidleech v3</h1>
<div align="center">
	
	<p>Link to Transload: <input size="100" id="DownloadLink" type="text" name="link" value="Enter http:// or ftp:// link you want to transload"  onfocus="if(this.value=='Enter http:// or ftp:// link you want to transload'){this.value=''}" onblur="if(this.value==''){this.value='Enter http:// or ftp:// link you want to transload'}" /> <input type="button" onclick="transload();" value="Transload" /><br />
	[ <a href="javascript:moreLinks();">More &gt;&gt;</a> ]</p>
	<!-- Download Queue Table -->
	<table width="780px" id="dl_table" border=1>
		<thead>
			<tr>
				<th style="width: 280px">Link</th>
				<th style="width: 130px">Status</th>
				<th style="width: 70px">Size</th>
				<th style="width: 70px">Received</th>
				<th style="width: 185px">Progress</th>
				<th style="width: 70px">Speed</th>
			</tr>
		</thead>
		<tbody>
		</tbody>
	</table>
	<br />
	<form method="post" action="?mod=action" id="flist">
	<!-- Parameters for file renaming -->
	<script type="text/javascript">setVarsForm("mod=ajaxrename&path=<?php echo urlencode($path); ?>");</script>
	<table width="700px" border=1>
		<tr>
			<td colspan="5">
				<span style="float: left;">Path: <?php echo $path; ?> [ <a href="index.php?nav=<?php echo urlencode(substr($path,0,strrpos(substr($path,0,-1),'/')));?>">Up</a> ]</span>
				<span style="float: right;">[ <a href="javascript:createDir();">Create Dir</a> ]</span>
			</td>
		</tr>
		<tr>
			<td colspan="5">
				<span style="float: left;">Select:
					[ <a href="javascript:select('all');">All</a> ]
					[ <a href="javascript:select('none');">None</a> ]
					[ <a href="javascript:select('invert');">Inverted</a> ]
				</span>
				<span style="float: right;">Do:
					<select name="action">
						<option selected="selected">==Select Action==</option>
					</select>
				</span>
			</td>
		</tr>
	</table>
	<table width="700px" border=1 id="file_table">
		<thead>
			<tr>
				<th width="3%">&nbsp;</th>
				<th width="42%">File Name</th>
				<th width="15%">Size</th>
				<th width="20%">Time</th>
				<th width="20%">Actions</th>
			</tr>
		</thead>
		<tbody>
<?php
$TotalSize = 0;
foreach ($Files as $i=>$File) {
	if ($File['type'] == 'file') {
?>
			<tr>
				<td><input type="checkbox" name="files[]" value="<?php echo $File['name']; ?>" /></td>
				<td><span id="<?php echo htmlentities($File['name']); ?>" class="editText"><?php echo htmlentities($File['name']); ?></span></td>
				<td><?php echo byteConvert($File['size']); ?></td>
				<td><?php echo date('d-m-y H:i:s',$File['time']); ?></td>
				<td>&nbsp;</td>
			</tr>
<?php 
		$TotalSize += $File['size'];
	} elseif ($File['type'] == 'dir') {
?>
			<tr>
				<td>&nbsp;</td>
				<td><a href="index.php?nav=<?php echo urlencode(substr($File['realpath'],6)); ?>"><?php echo $File['name']; ?></a></td>
				<td><?php echo byteConvert($File['size']); ?></td>
				<td><?php echo date('d-m-y H:i:s',$File['time']); ?></td>
				<td>&nbsp;</td>
			</tr>
<?php 
	}
}
?>
		</tbody>
		<tfoot>
			<tr>
				<td colspan="5" class="sortbottom">
					Total <b><?php echo count($Files); ?></b> items (<b><?php echo byteConvert($TotalSize); ?></b>)
				</td>
			</tr>
		</tfoot>
	</table>
	</form>
<!-- Initialize sortable table -->
<script type="text/javascript">
jQuery(document).ready(function() {
	jQuery('#file_table').dataTable({
		"bSort": true,
		"aoColumns": [
		      		{ "bSortable": false },
		      		{ "bSortable": true,
			      		"sType": "string" },
		      		{ "bSortable": true },
		      		{ "bSortable": true },
		      		{ "bSortable": false }],
		"bPaginate": false,
		"bFilter": false,
		"bInfo": false
	});
})
</script>
</div>
