<html>
	<head>
		<title>Rapidleech v3 Dev Build</title>
		<script type="text/javascript" src="<?php echo htmlpath($template_path.'/js/rapidleech.js'); ?>"></script>
		<link type="text/css" href="<?php echo htmlpath($template_path.'/css/ui.all.css'); ?>" rel="stylesheet" />
		<!-- <script type="text/javascript" src="js/rapidleech.js"></script> -->
		<script type="text/javascript" src="js/jquery-1.3.2.min.js"></script>
		<script type="text/javascript" src="js/jquery-ui-1.7.1.custom.min.js"></script>
		<script type="text/javascript" src="js/jquery.dataTables.min.js"></script>
		<script type="text/javascript" src="js/prototype.js"></script>
		<script type="text/javascript" src="js/jsProgressBarHandler.js"></script>
		<script type="text/javascript" src="js/instantedit.js"></script>
	</head>
	
	<body>
	